// ui/src/App.svelte
<script lang="ts">
    import "./assets/css/app.css";
    import {onMount} from "svelte";
    import {Router} from "svelte-navigator";
    import Portal from "svelte-portal";
    import {theme} from "@/stores/themeStore";
    import {alert} from "@/stores/alertStore";
    import {auth} from "@/stores/authStore";
    import {breakpoint} from "@/stores/breakpointStore";
    import {NavbarBase, NavbarUser, AlertDefault, NavbarGuest} from "@/components";
    import LazyRoute from "@/pages/LazyRoute.svelte";
    import PublicRoute from "@/pages/PublicRoute.svelte";
    import PrivateRoute from "@/pages/PrivateRoute.svelte";
    import LoadingPage from "@/components/loadings/LoadingPage.svelte";
    
    const delayModuleLoad = module =>
        new Promise(res =>
            setTimeout(() => res(module), Math.random() * 2000),
        );

    const Login = () => import("./pages/Login.svelte").then(delayModuleLoad);
    const Dashboard = () => import("./pages/protected/Dashboard.svelte").then(delayModuleLoad);

    function onResize() {
        const width = window.screen.width;

        if (320 <= width && 768 >= width) {
            breakpoint.set(true);
        } else {
            breakpoint.set(false);
        }
    }

    onMount(() => {
        if ($theme === "dark") {
            document.documentElement.classList.add("dark");
            window.localStorage.setItem("theme", "dark");
        } else {
            document.documentElement.classList.remove("dark");
            window.localStorage.setItem("theme", "light");
        }

        onResize();

        window.addEventListener("resize", onResize);

        return () => window.removeEventListener("resize", onResize); // destroy
    });
</script>

<Router>
    <NavbarBase>
        {#if $auth.isAuthenticated}
            <NavbarUser/>
        {:else }
            <NavbarGuest/>
        {/if}
    </NavbarBase>
    <main class="lg:px-2.5 lg:pb-2.5">
        <PublicRoute path="login" let:location>
            <LazyRoute component={Login} delayMs={500}>
                <LoadingPage/>
            </LazyRoute>
        </PublicRoute>

        <PrivateRoute path="protected/dashboard" let:location>
            <LazyRoute component={Dashboard} delayMs={500}>
                <LoadingPage/>
            </LazyRoute>
        </PrivateRoute>
    </main>
</Router>

<Portal target="body">
    {#if $alert.show}
        <AlertDefault/>
    {/if}
</Portal>

// ui/src/App.vue
<script lang="ts" setup>
import {onBeforeUnmount, onMounted} from "vue";
import {useBreakPointStore} from "@/stores/breakpoint";
import {useAlertStore} from "@/stores/alert";
import {useAuthStore} from "@/stores/auth";
import {NavbarBase, NavbarGuest, NavbarProtected, AlertDefault} from "@/components";

const breakPointStore = useBreakPointStore();
const alertStore = useAlertStore();
const authStore = useAuthStore();

function onResize() {
  const width = window.screen.width;

  if (320 <= width && 768 >= width) {
    breakPointStore.updateCheckMobile(true);
  } else {
    breakPointStore.updateCheckMobile(false);
  }
}

onMounted(async () => {
  if (localStorage.getItem("theme") == null) {
    document.documentElement.classList.remove("dark");
  } else {
    if (localStorage.getItem("theme") === "light") {
      document.documentElement.classList.remove("dark");
    } else {
      document.documentElement.classList.add("dark");
    }
  }

  const width = window.screen.width;

  if (320 <= width && 768 >= width) {
    breakPointStore.updateCheckMobile(true);
  } else {
    breakPointStore.updateCheckMobile(false);
  }

  window.addEventListener("resize", onResize);
});

onBeforeUnmount(() => {
  window.removeEventListener("resize", onResize);
});
</script>

<template>
  <NavbarBase>
    <NavbarProtected v-if="authStore.getStatusAuthenticated"/>
    <NavbarGuest v-else/>
  </NavbarBase>
  <main class="lg:px-2.5 lg:pb-2.5">
    <RouterView/>
  </main>
  <Teleport to="body">
    <Transition enter-active-class="animate__animated animate__fadeInRight"
                leave-active-class="animate__animated animate__fadeOutRight">
      <AlertDefault v-if="alertStore.getAlert.show"/>
    </Transition>
  </Teleport>
</template>
