// ui/src/components/mobile/MobileNavbar.vue
<script lang="ts" setup>
import Notification from "@/components/Notification.vue";
import ProfileMobile from "@/components/mobile/MobileProfile.vue";

</script>

<template>
  <div class="flex flex-row flex-nowrap mr-2">
    <div class="flex-1">
      <Notification />
    </div>
    <div class="flex-none">
      <ProfileMobile />
    </div>
  </div>
</template>

// ui/src/components/mobiles/MobileNavbar.svelte
<script lang="ts">
    import Portal from "svelte-portal";
    import {Notification, MobileProfile, MobileProfileBox} from "@/components";

    let isOpenBox: boolean = false;

    function onToggleProfileBox(event) {
        isOpenBox = event.detail.value;
    }
</script>

<div class="flex flex-row flex-nowrap mr-2">
    <div class="flex-1">
        <Notification/>
    </div>
    <div class="flex-none">
        <MobileProfile on:show={onToggleProfileBox}/>
    </div>
</div>

<Portal to="body">
    {#if isOpenBox}
        <MobileProfileBox on:hide={onToggleProfileBox}/>
    {/if}
</Portal>
