// ui/src/components/Mobile/MobileNavbar.vue
<script lang="ts" setup>
import {ref} from "vue";
import {Notification, MobileProfile, MobileProfileBox} from "@/components";

const openProfileBox = ref<boolean>(false);

function onToggleProfileBox(value: boolean) {
  openProfileBox.value = value;
}
</script>

<template>
  <div class="flex flex-row flex-nowrap mr-2">
    <div class="flex-1">
      <Notification/>
    </div>
    <div class="flex-none">
      <MobileProfile @onShowProfileBox="onToggleProfileBox"/>
    </div>
  </div>
  <Teleport to="body">
    <Transition enter-active-class="animate__animated animate__fadeInUp"
                leave-active-class="animate__animated animate__fadeOutDown">
      <MobileProfileBox v-if="openProfileBox" @onCloseProfileBox="onToggleProfileBox"/>
    </Transition>
  </Teleport>
</template>

// ui/src/components/mobiles/MobileNavbar.svelte
<script lang="ts">
    import Portal from "svelte-portal";
    import {Notification, MobileProfile, MobileProfileBox} from "@/components";

    let isOpenBox: boolean = false;

    function onToggleProfileBox(event) {
        isOpenBox = event.detail.value;
    }
</script>

<div class="flex flex-row flex-nowrap mr-2">
    <div class="flex-1">
        <Notification/>
    </div>
    <div class="flex-none">
        <MobileProfile on:show={onToggleProfileBox}/>
    </div>
</div>

<Portal to="body">
    {#if isOpenBox}
        <MobileProfileBox on:hide={onToggleProfileBox}/>
    {/if}
</Portal>
