// ui/src/components/alerts/AlertDefault.svelte
<script lang="ts">
    import {onMount} from "svelte";
    import {fade} from "svelte/transition";
    import {IconAlert, IconAlertBox, IconAlertCircle, IconCheckCircle} from "@/components";
    import {alertStore} from "@/stores/alertStore";
    import {breakpoint} from "@/stores/breakpointStore";

    const icon = {
        success: IconCheckCircle,
        error: IconAlert,
        warning: IconAlertCircle,
        info: IconAlertBox,
    };

    const text = {
        success: "Success Message",
        error: "Error Message",
        warning: "Warning Message",
        info: "Information",
    };

    const btnClass = {
        success: "btn-success",
        error: "btn-error",
        warning: "btn-warning",
        info: "btn-default",
    };

    function hideAlert() {
        alertStore.update((state) => {
            return {...state, show: false};
        });
    }

    let timeout: number;
    onMount(() => {
        timeout = setTimeout(hideAlert, 5000);

        return () => clearTimeout(timeout); // destroy
    });
</script>

<div transition:fade
     role="alert"
     class="alert p-4 mb-4 text-white border rounded-lg fixed w-auto {$alert.type} {$breakpoint ? 'top-center':'bottom-right'}">
    <div class="flex items-center">
        <svelte:component this={icon[$alert.type]} className="icon mr-2 w-6 h-6 text-white"/>
        <h3 class="text-lg font-medium text-white">{text[$alert.type]}</h3>
    </div>
    <div class="mt-2 mb-4 text-sm text-white">
        {$alert.text}
    </div>
    <div class="flex">
        <button type="button"
                class="btn-alert text-white font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none focus:ring-2 {btnClass[$alert.type]}"
                on:click={hideAlert}>
            Tutup
        </button>
    </div>
</div>

// ui/src/components/alert/AlertDefault.vue
<script lang="ts" setup>
import {ref,computed,onMounted,onBeforeUnmount} from "vue"
import {useBreakPointStore} from "@/stores/breakpoint"
import {useAlertStore} from "@/stores/alert"
import IconAlert from "@/components/icon/IconAlert.vue";
import IconAlertBox from "@/components/icon/IconAlertBox.vue";
import IconAlertCircle from "@/components/icon/IconAlertCircle.vue";
import IconCheckCircle from "@/components/icon/IconCheckCircle.vue";
import ButtonAlert from "@/components/button/ButtonAlert.vue";

const breakPointStore = useBreakPointStore()
const alertStore = useAlertStore()

let time = ref<null|number>(null)

const position = computed(() => {
  return breakPointStore.checkIsMobile ? "top-center" : "bottom-right"
})

const text = computed(() => {
  if(alertStore.getAlert.type === "success") {
    return "Success Message"
  }

  if(alertStore.getAlert.type === "error") {
    return "Error Message"
  }

  if(alertStore.getAlert.type === "warning") {
    return "Warning Message"
  }

  return "Information"
})

function onClose() {
  alertStore.$reset()
}

onMounted(() => {
  time.value = setTimeout(() => {
    alertStore.$reset()
  }, 5000)
})

onBeforeUnmount(() => {
  clearTimeout(time.value!)
})
</script>

<template>
  <div role="alert" class="alert p-4 mb-4 text-white border rounded-lg fixed w-auto" :class="[position, alertStore.getAlert.type]">
    <div class="flex items-center">
      <template v-if="alertStore.getAlert.type === 'success'">
        <IconCheckCircle className="mr-2 w-6 h-6 text-white"/>
      </template>
      <template v-else-if="alertStore.getAlert.type === 'error'">
        <IconAlert className="mr-2 w-6 h-6 text-white"/>
      </template>
      <template v-else-if="alertStore.getAlert.type === 'warning'">
        <IconAlertCircle className="mr-2 w-6 h-6 text-white"/>
      </template>
      <template v-else>
        <IconAlertBox className="mr-2 w-6 h-6 text-white"/>
      </template>
      <h3 class="text-lg font-medium text-white">{{ text }}</h3>
    </div>
    <div class="mt-2 mb-4 text-sm text-white">
      {{ alertStore.getAlert.text }}
    </div>
    <div class="flex">
      <ButtonAlert label="Tutup" @onClick="onClose" />
    </div>
  </div>
</template>
